#!/bin/bash

if [[ "$@" == *"fbneo_libretro"* ]]; then
  vertmode=$(cat /home/ark/.config/retroarch/retroarch-core-options.cfg | grep "fbneo-vertical-mode" | grep -oP '"\K[^"]+')
  sed -i '/fbneo-vertical-mode \=/c\fbneo-vertical-mode \= "alternate"' /home/ark/.config/retroarch/retroarch-core-options.cfg
  core="fbneo"
elif [[ "$@" == *"mame2003_plus_libretro"* ]]; then
  vertmode=$(cat /home/ark/.config/retroarch/retroarch-core-options.cfg | grep "mame2003-plus_tate_mode" | grep -oP '"\K[^"]+')
  sed -i '/mame2003-plus_tate_mode \=/c\mame2003-plus_tate_mode \= "enabled"' /home/ark/.config/retroarch/retroarch-core-options.cfg
  core="mame2003_plus"
fi

/opt/retroarch/bin/retroarch -c /home/ark/.config/retroarch/retroarch.cfg --appendconfig=/home/ark/.config/retroarch/retroarch.cfg.vert -L /home/ark/.config/retroarch/cores/"$core"_libretro.so "$3"

if [[ "$@" == *"fbneo_libretro"* ]]; then
  sed -i '/fbneo-vertical-mode \=/c\fbneo-vertical-mode \= "$vertmode"' /home/ark/.config/retroarch/retroarch-core-options.cfg
elif [[ "$@" == *"mame2003_plus_libretro"* ]]; then
  sed -i '/mame2003-plus_tate_mode \=/c\mame2003-plus_tate_mode \= "$vertmode"' /home/ark/.config/retroarch/retroarch-core-options.cfg
fi

