#!/bin/bash

rootdirectory=$(dirname "$3" | cut -d "/" -f2)
romsdirectory=$(dirname "$3" | cut -d "/" -f3)

rm -rf ~/.mednafen/firmware
rm -rf ~/.mednafen/sav
rm -rf ~/.mednafen/mcs
rm -rf ~/.mednafen/b


ln -s /$rootdirectory/bios ~/.mednafen/firmware
ln -s /$rootdirectory/$romsdirectory ~/.mednafen/sav
ln -s /$rootdirectory/$romsdirectory ~/.mednafen/mcs
ln -s /$rootdirectory/$romsdirectory ~/.mednafen/b

if [[ "$2" != *"norecord"* ]]; then
  recordingname=$(echo "/$rootdirectory/videos/recordings/$(ls "$3" | cut -d "/" -f4)$RANDOM.mov")
  reqSpace=500000
  availSpace=$(df "/$rootdirectory" | awk 'NR==2 { print $4 }')
  if (( availSpace < reqSpace )); then
    printf "Not enough space to safely record this gameplay to $recordingname." >> /dev/tty1
    printf "\nYou need at least 500MBs of space left before" >> /dev/tty1
    printf "\na recording can be created for this gameplay." >> /dev/tty1
    sleep 10
    printf "\033c" >> /dev/tty1
    exit 1
  fi
  if [ ! -d "/$rootdirectory/videos/recordings" ]; then
   mkdir /$rootdirectory/videos/recordings
  fi
  if [ -f "$recordingname" ]; then
   rm -f "$recordingname"
  fi
  printf "\033c" >> /dev/tty1
  printf "\033[1;33m" >> /dev/tty1
  printf "\n This game play will be recorded to $recordingname" >> /dev/tty1
  printf "\n Be aware that this recording can use quite a bit of space." >> /dev/tty1
  printf "\n and can cause random emulation pauses during recording writes." >> /dev/tty1
  sleep 10
  printf "\033c" >> /dev/tty1
  if [ "$romsdirectory" == "snes" ] || [ "$romsdirectory" == "sfc" ] || [ "$romsdirectory" == "snes-hacks" ]; then
    /opt/mednafen/mednafen -force_module snes_faust -qtrecord "$recordingname" "$3"
  else
    /opt/mednafen/mednafen -qtrecord "$recordingname" "$3"
  fi
else
  if [ "$romsdirectory" == "snes" ] || [ "$romsdirectory" == "sfc" ] || [ "$romsdirectory" == "snes-hacks" ]; then
    /opt/mednafen/mednafen -force_module snes_faust "$3"
  else
    /opt/mednafen/mednafen "$3"
  fi
fi
