#!/bin/bash

if [ -f "/opt/system/Advanced/Switch to main SD for Roms.sh" ]; then
  directory="roms2"
else
  directory="roms"
fi

if [[ ! -d "/$directory/bios/openmsx" ]]; then
  cp -rf /opt/openmsx/backupconfig/openmsx  /$directory/bios
fi

if [[ ! -f "/$directory/bios/openmsx/openmsx.gptk" ]]; then
  cp -f /opt/openmsx/backupconfig/openmsx/openmsx.gptk /$directory/bios/openmsx/openmsx.gptk
fi

if [[ ! -f "/$directory/bios/openmsx/commands.txt" ]]; then
  cp -f /opt/openmsx/backupconfig/openmsx/commands.txt /$directory/bios/openmsx/commands.txt
fi

if [[ ! -z $(cat /etc/emulationstation/es_input.cfg | grep "190000004b4800000010000001010000") ]] || [[ -e "/dev/input/by-path/platform-gameforce-gamepad-event-joystick" ]]; then
  export HOTKEY="l3"
fi

sudo chmod 666 /dev/uinput
cd /opt/openmsx
export OPENMSX_USER_DATA="/$directory/bios/openmsx/share"
export OPENMSX_HOME=$(dirname "$3")
export SDL_GAMECONTROLLERCONFIG_FILE="./gamecontrollerdb.txt" 
./gptokeyb -1 "openmsx" -c "/$directory/bios/openmsx/openmsx.gptk" &
LD_LIBRARY_PATH=libs/ ./openmsx -script "/$directory/bios/openmsx/commands.txt" "$3" "$4" "$5"
unset SDL_GAMECONTROLLERCONFIG_FILE
sudo kill -9 $(pidof gptokeyb)
sudo systemctl restart oga_events &
printf "\033c" >> /dev/tty1

