#!/bin/bash
printf "\033c" >> /dev/tty1

if [[ "$(tr -d '\0' < /proc/device-tree/compatible)" == *"rk3326"* ]]; then
  isitrk3326="True"
  gpu="ff400000"
else
  isitrk3326=""
  gpu="fde60000"
fi

if [[ ! -z "$isitrk3326" ]]; then
  rm /home/ark/.asoundrc
fi

if [ -f "/roms/launchimages/loading.jpg" ]; then
  ffplay -x 1280 -y 720 /roms/launchimages/loading.jpg &
  PROC=$!
  (sleep 2s; kill -9 $PROC)
fi

chmod 777 /sys/devices/platform/${gpu}.gpu/devfreq/${gpu}.gpu/governor
chmod 777 /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
chmod 777 /sys/devices/platform/dmc/devfreq/dmc/governor

if [[ "$1" != "ondemand" ]]; then
  echo "$1" > /sys/devices/platform/${gpu}.gpu/devfreq/${gpu}.gpu/governor
  echo "$1" > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
  echo "$1" > /sys/devices/platform/dmc/devfreq/dmc/governor
else
  echo simple_"$1" > /sys/devices/platform/${gpu}.gpu/devfreq/${gpu}.gpu/governor
  echo "$1" > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
  echo dmc_"$1" > /sys/devices/platform/dmc/devfreq/dmc/governor
fi
