#!/bin/bash

if [[ -e "/dev/input/by-path/platform-ff300000.usb-usb-0:1.2:1.0-event-joystick" ]]; then
  event_num="3"
  event_type="EV_KEY"
  event_btn="BTN_SOUTH"
elif [[ -e "/dev/input/by-path/platform-odroidgo2-joypad-event-joystick" ]]; then
  event_num="2"
  event_type="EV_KEY"
  event_btn="BTN_EAST"
elif [[ -e "/dev/input/by-path/platform-odroidgo3-joypad-event-joystick" ]]; then
  event_num="2"
  event_type="EV_KEY"
  event_btn="BTN_EAST"
elif [[ -e "/dev/input/by-path/platform-gameforce-gamepad-event-joystick" ]]; then
  event_num="2"
  event_type="EV_KEY"
  event_btn="BTN_EAST"
elif [[ -e "/dev/input/by-path/platform-singleadc-joypad-event-joystick" ]]; then
  event_num="3"
  event_type="EV_KEY"
  event_btn="BTN_EAST"
fi

filename=$(basename "$3")
filename="${filename%.*}"

directory=$(dirname "$3" | cut -d "/" -f2)

if [ ! -d "/$directory/psx/savestates" ]; then
    mkdir -p "/$directory/psx/savestates"
fi

if [ -d "$HOME/.config/duckstation/savestates" ]; then
    rm -rf "$HOME/.config/duckstation/savestates"
fi

ln -sfv "/$directory/psx/savestates" "$HOME/.config/duckstation/savestates"

evtest --query /dev/input/event$event_num $event_type $event_btn
if [ "$?" -eq "10" ]; then
  printf "\033c" >> /dev/tty1
  printf "\033[1;33m" >> /dev/tty1
  if [ ! -d "/$directory/psx/duckstation_gamesettings" ]; then
      printf "\n Creating /$directory/psx/duckstation_gamesettings/${filename}.settings.ini" >> /dev/tty1
      mkdir -p "/$directory/psx/duckstation_gamesettings"
  else
      printf "\n /$directory/psx/duckstation_gamesettings/${filename}.settings.ini" >> /dev/tty1
      printf "\n already exist!" >> /dev/tty1
  fi
  sleep 3
  printf "\033c" >> /dev/tty1
  printf "\033[0m" >> /dev/tty1
  if [ ! -f "/$directory/psx/duckstation_gamesettings/${filename}.settings.ini" ]; then
      cp "$HOME/.config/duckstation/settings.ini" "/$directory/psx/duckstation_gamesettings/${filename}.settings.ini"
  fi
  duckstation-nogui -fullscreen -settings "/$directory/psx/duckstation_gamesettings/${filename}.settings.ini" -- "${3}" > /dev/null 2>&1
else
  if [ -f "/$directory/psx/duckstation_gamesettings/${filename}.settings.ini" ]; then
    duckstation-nogui -fullscreen -settings "/$directory/psx/duckstation_gamesettings/${filename}.settings.ini" -- "${3}" > /dev/null 2>&1
  else
    duckstation-nogui -fullscreen -settings "$HOME/.config/duckstation/settings.ini" -- "${3}" > /dev/null 2>&1
  fi
fi
